//文章管理
export const CLEAR_ARTICLE_DETAIL = 'CLEAR_ARTICLE_DETAIL'
export const CLEAR_SUB_ARTICLE = 'CLEAR_SUB_ARTICLE'
export const CLEAR_SUB_ARTICLE_DETAIL = 'CLEAR_SUB_ARTICLE_DETAIL'

export const FILTER_ARTICLES_DETAIL = 'FILTER_ARTICLES_DETAIL'
export const FILTER_ARTICLES_DETAIL_SUCCESS = 'FILTER_ARTICLES_DETAIL_SUCCESS'
export const FILTER_ARTICLES_DETAIL_FAILURE = 'FILTER_ARTICLES_DETAIL_FAILURE'

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS'
export const FILTER_PRODUCTS_FAILURE = 'FILTER_PRODUCTS_FAILURE'

export const FILTER_BRANDS = 'FILTER_BRANDS'
export const FILTER_BRANDS_SUCCESS = 'FILTER_BRANDS_SUCCESS'
export const FILTER_BRANDS_FAILURE = 'FILTER_BRANDS_FAILURE'

export const FILTER_NEWS = 'FILTER_NEWS'
export const FILTER_NEWS_SUCCESS = 'FILTER_NEWS_SUCCESS'
export const FILTER_NEWS_FAILURE = 'FILTER_NEWS_FAILURE'

export const FILTER_EVALUATING = 'FILTER_EVALUATING'
export const FILTER_EVALUATING_SUCCESS = 'FILTER_EVALUATING_SUCCESS'
export const FILTER_EVALUATING_FAILURE = 'FILTER_EVALUATING_FAILURE'

export const FILTER_VIDEOS = 'FILTER_VIDEOS'
export const FILTER_VIDEOS_SUCCESS = 'FILTER_VIDEOS_SUCCESS'
export const FILTER_VIDEOS_FAILURE = 'FILTER_VIDEOS_FAILURE'

export const FILTER_BROADCAST = 'FILTER_BROADCAST'
export const FILTER_BROADCAST_SUCCESS = 'FILTER_BROADCAST_SUCCESS'
export const FILTER_BROADCAST_FAILURE = 'FILTER_BROADCAST_FAILURE'

export const FILTER_TUNE = 'FILTER_TUNE'
export const FILTER_TUNE_SUCCESS = 'FILTER_TUNE_SUCCESS'
export const FILTER_TUNE_FAILURE = 'FILTER_TUNE_FAILURE'

export const FILTER_SUB_ARTICLE = 'FILTER_SUB_ARTICLE'
export const FILTER_SUB_ARTICLE_SUCCESS = 'FILTER_SUB_ARTICLE_SUCCESS'
export const FILTER_SUB_ARTICLE_FAILURE = 'FILTER_SUB_ARTICLE_FAILURE'

export const FILTER_SUB_ARTICLE_DETAIL = 'FILTER_SUB_ARTICLE_DETAIL'
export const FILTER_SUB_ARTICLE_DETAIL_SUCCESS = 'FILTER_SUB_ARTICLE_DETAIL_SUCCESS'
export const FILTER_SUB_ARTICLE_DETAIL_FAILURE = 'FILTER_SUB_ARTICLE_DETAIL_FAILURE'

//周刊录入
export const FILTER_RECOMMEND = 'FILTER_RECOMMEND'
export const FILTER_RECOMMEND_SUCCESS = 'FILTER_RECOMMEND_SUCCESS'
export const FILTER_RECOMMEND_FAILURE = 'FILTER_RECOMMEND_FAILURE'

//配置管理
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'

export const CLEAR_CONFIGS_DETAIL = 'CLEAR_CONFIGS_DETAIL'

export const FILTER_CONFIGS_DETAIL = 'FILTER_CONFIGS_DETAIL'
export const FILTER_CONFIGS_DETAIL_SUCCESS = 'FILTER_CONFIGS_DETAIL_SUCCESS'
export const FILTER_CONFIGS_DETAIL_FAILURE = 'FILTER_CONFIGS_DETAIL_FAILURE'

export const FILTER_PRODUPREMOVAL = 'FILTER_PRODUPREMOVAL'
export const FILTER_PRODUPREMOVAL_SUCCESS = 'FILTER_PRODUPREMOVAL_SUCCESS'
export const FILTER_PRODUPREMOVAL_FAILURE = 'FILTER_PRODUPREMOVAL_FAILURE'

export const FILTER_TOPICS = 'FILTER_TOPICS'
export const FILTER_TOPICS_SUCCESS = 'FILTER_TOPICS_SUCCESS'
export const FILTER_TOPICS_FAILURE = 'FILTER_TOPICS_FAILURE'

export const FILTER_CHANNELS = 'FILTER_CHANNELS'
export const FILTER_CHANNELS_SUCCESS = 'FILTER_CHANNELS_SUCCESS'
export const FILTER_CHANNELS_FAILURE = 'FILTER_CHANNELS_FAILURE'

export const FILTER_SEEDS = 'FILTER_SEEDS'
export const FILTER_SEEDS_SUCCESS = 'FILTER_SEEDS_SUCCESS'
export const FILTER_SEEDS_FAILURE = 'FILTER_SEEDS_FAILURE'

export const FILTER_LINKS = 'FILTER_LINKS';
export const FILTER_LINKS_SUCCESS = 'FILTER_LINKS_SUCCESS';
export const FILTER_LINKS_FAILURE = 'FILTER_LINKS_FAILURE';

export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';
export const FILTER_CATEGORIES_SUCCESS = 'FILTER_CATEGORIES_SUCCESS';
export const FILTER_CATEGORIES_FAILURE = 'FILTER_CATEGORIES_FAILURE';

export const FILTER_DICTIONARY = 'FILTER_DICTIONARY'
export const FILTER_DICTIONARY_SUCCESS = 'FILTER_DICTIONARY_SUCCESS'
export const FILTER_DICTIONARY_FAILURE = 'FILTER_DICTIONARY_FAILURE'

export const FILTER_BOOST = 'FILTER_BOOST'
export const FILTER_BOOST_SUCCESS = 'FILTER_BOOST_SUCCESS'
export const FILTER_BOOST_FAILURE = 'FILTER_BOOST_FAILURE'

export const FILTER_LABELQUERY = 'FILTER_LABELQUERY'
export const FILTER_LABELQUERY_SUCCESS = 'FILTER_LABELQUERY_SUCCESS'
export const FILTER_LABELQUERY_FAILURE = 'FILTER_LABELQUERY_FAILURE'

//翻译管理
export const CLEAR_TRANSLATE_DETAIL = 'CLEAR_TRANSLATE_DETAIL'

export const FILTER_TRANSLATE_DETAIL = 'FILTER_TRANSLATE_DETAIL'
export const FILTER_TRANSLATE_DETAIL_SUCCESS = 'FILTER_TRANSLATE_DETAIL_SUCCESS'
export const FILTER_TRANSLATE_DETAIL_FAILURE = 'FILTER_TRANSLATE_DETAIL_FAILURE'

export const FILTER_TASKS = 'FILTER_TASKS'
export const FILTER_TASKS_SUCCESS = 'FILTER_TASKS_SUCCESS'
export const FILTER_TASKS_FAILURE = 'FILTER_TASKS_FAILURE'

export const FILTER_TRANSLATE_HOPE = 'FILTER_TRANSLATE_HOPE';
export const FILTER_TRANSLATE_HOPE_SUCCESS = 'FILTER_TRANSLATE_HOPE_SUCCESS';
export const FILTER_TRANSLATE_HOPE_FAILURE = 'FILTER_TRANSLATE_HOPE_FAILURE';

export const FILTER_TRANSLATE_AUDIT = 'FILTER_TRANSLATE_AUDIT';
export const FILTER_TRANSLATE_AUDIT_SUCCESS = 'FILTER_TRANSLATE_AUDIT_SUCCESS';
export const FILTER_TRANSLATE_AUDIT_FAILURE = 'FILTER_TRANSLATE_AUDIT_FAILURE';

//问卷管理
export const UPLOAD_BACKIMG_SUCCESS = 'UPLOAD_BACKIMG_SUCCESS'

export const CLEAR_QUESTION_DETAIL = 'CLEAR_QUESTION_DETAIL'

export const FILTER_QUESTION_DETAIL = 'FILTER_QUESTION_DETAIL'
export const FILTER_QUESTION_DETAIL_SUCCESS = 'FILTER_QUESTION_DETAIL_SUCCESS'
export const FILTER_QUESTION_DETAIL_FAILURE = 'FILTER_QUESTION_DETAIL_FAILURE'

export const FILTER_QUIZS = 'FILTER_QUIZS'
export const FILTER_QUIZS_SUCCESS = 'FILTER_QUIZS_SUCCESS'
export const FILTER_QUIZS_FAILURE = 'FILTER_QUIZS_FAILURE'

export const FILTER_QUIZSCOUNT = 'FILTER_QUIZSCOUNT'
export const FILTER_QUIZSCOUNT_SUCCESS = 'FILTER_QUIZSCOUNT_SUCCESS'
export const FILTER_QUIZSCOUNT_FAILURE = 'FILTER_QUIZSCOUNT_FAILURE'

//数据中心
export const CLEAR_DATACENTER_DETAIL = 'CLEAR_DATACENTER_DETAIL'

export const FILTER_DATACENTER_DETAIL = 'FILTER_DATACENTER_DETAIL'
export const FILTER_DATACENTER_DETAIL_SUCCESS = 'FILTER_DATACENTER_DETAIL_SUCCESS'
export const FILTER_DATACENTER_DETAIL_FAILURE = 'FILTER_DATACENTER_DETAIL_FAILURE'

export const FILTER_RANK = 'FILTER_RANK'
export const FILTER_RANK_SUCCESS = 'FILTER_RANK_SUCCESS'
export const FILTER_RANK_FAILURE = 'FILTER_RANK_FAILURE'

export const FILTER_LOGDICTIONARY = 'FILTER_LOGDICTIONARY';
export const FILTER_LOGDICTIONARY_SUCCESS = 'FILTER_LOGDICTIONARY_SUCCESS';
export const FILTER_LOGDICTIONARY_FAILURE = 'FILTER_LOGDICTIONARY_FAILURE';

export const FILTER_OUTLINE = 'FILTER_OUTLINE';
export const FILTER_OUTLINE_SUCCESS = 'FILTER_OUTLINE_SUCCESS';
export const FILTER_OUTLINE_FAILURE = 'FILTER_OUTLINE_FAILURE';

export const FILTER_TOPICMODEL = 'FILTER_TOPICMODEL'
export const FILTER_TOPICMODEL_SUCCESS = 'FILTER_TOPICMODEL_SUCCESS'
export const FILTER_TOPICMODEL_FAILURE = 'FILTER_TOPICMODEL_FAILURE'





/*---------------------------- 旧的 ----------------------------*/

export const CLEAR_DATA = 'CLEAR_DATA'

//filterMessage Actions
export const FILTER_MESSAGE = 'FILTER_MESSAGE';
export const FILTER_MESSAGE_SUCCESS = 'FILTER_MESSAGE_SUCCESS';
export const FILTER_MESSAGE_FAILURE = 'FILTER_MESSAGE_FAILURE';

//filterMessageDetail Actions
export const FILTER_MESSAGE_DETAIL = 'FILTER_MESSAGE_DETAIL';
export const FILTER_MESSAGE_DETAIL_SUCCESS = 'FILTER_MESSAGE_DETAIL_SUCCESS';
export const FILTER_MESSAGE_DETAIL_FAILURE = 'FILTER_MESSAGE_DETAIL_FAILURE';

//filterReport Actions
export const FILTER_REPORT = 'FILTER_REPORT';
export const FILTER_REPORT_SUCCESS = 'FILTER_REPORT_SUCCESS';
export const FILTER_REPORT_FAILURE = 'FILTER_REPORT_FAILURE';

//filterReportDetail Actions
export const FILTER_REPORT_DETAIL = 'FILTER_REPORT_DETAIL';
export const FILTER_REPORT_DETAIL_SUCCESS = 'FILTER_REPORT_DETAIL_SUCCESS';
export const FILTER_REPORT_DETAIL_FAILURE = 'FILTER_REPORT_DETAIL_FAILURE';

//filterFeedback Actions
export const FILTER_FEEDBACK = 'FILTER_FEEDBACK';
export const FILTER_FEEDBACK_SUCCESS = 'FILTER_FEEDBACK_SUCCESS';
export const FILTER_FEEDBACK_FAILURE = 'FILTER_FEEDBACK_FAILURE';

//filterFeedbackDetail Actions
export const FILTER_FEEDBACK_DETAIL = 'FILTER_FEEDBACK_DETAIL';
export const FILTER_FEEDBACK_DETAIL_SUCCESS = 'FILTER_FEEDBACK_DETAIL_SUCCESS';
export const FILTER_FEEDBACK_DETAIL_FAILURE = 'FILTER_FEEDBACK_DETAIL_FAILURE';

//filterNotices Actions
export const FILTER_NOTICES = 'FILTER_NOTICES';
export const FILTER_NOTICES_SUCCESS = 'FILTER_NOTICES_SUCCESS';
export const FILTER_NOTICES_FAILURE = 'FILTER_NOTICES_FAILURE';

//filterNoticesDetail Actions
export const FILTER_NOTICES_DETAIL = 'FILTER_NOTICES_DETAIL';
export const FILTER_NOTICES_DETAIL_SUCCESS = 'FILTER_NOTICES_DETAIL_SUCCESS';
export const FILTER_NOTICES_DETAIL_FAILURE = 'FILTER_NOTICES_DETAIL_FAILURE';

//filterDbCategories Actions
export const FILTER_DBCATEGORIES = 'FILTER_DBCATEGORIES';
export const FILTER_DBCATEGORIES_SUCCESS = 'FILTER_DBCATEGORIES_SUCCESS';
export const FILTER_DBCATEGORIES_FAILURE = 'FILTER_DBCATEGORIES_FAILURE';

//filterDbCategoriesDetail Actions
export const FILTER_DBCATEGORIES_DETAIL = 'FILTER_DBCATEGORIES_DETAIL';
export const FILTER_DBCATEGORIES_DETAIL_SUCCESS = 'FILTER_DBCATEGORIES_DETAIL_SUCCESS';
export const FILTER_DBCATEGORIES_DETAIL_FAILURE = 'FILTER_DBCATEGORIES_DETAIL_FAILURE';

//filterUser Actions
export const FILTER_USER = 'FILTER_USER';
export const FILTER_USER_SUCCESS = 'FILTER_USER_SUCCESS';
export const FILTER_USER_FAILURE = 'FILTER_USER_FAILURE';

//filterUserDetail Actions
export const FILTER_USER_DETAIL = 'FILTER_USER_DETAIL';
export const FILTER_USER_DETAIL_SUCCESS = 'FILTER_USER_DETAIL_SUCCESS';
export const FILTER_USER_DETAIL_FAILURE = 'FILTER_USER_DETAIL_FAILURE';

//filterSites Actions
export const FILTER_SITES = 'FILTER_SITES';
export const FILTER_SITES_SUCCESS = 'FILTER_SITES_SUCCESS';
export const FILTER_SITES_FAILURE = 'FILTER_SITES_FAILURE';

//filterSitesDetail Actions
export const FILTER_SITES_DETAIL = 'FILTER_SITES_DETAIL';
export const FILTER_SITES_DETAIL_SUCCESS = 'FILTER_SITES_DETAIL_SUCCESS';
export const FILTER_SITES_DETAIL_FAILURE = 'FILTER_SITES_DETAIL_FAILURE';

//filterGroups Actions
export const FILTER_GROUPS = 'FILTER_GROUPS';
export const FILTER_GROUPS_SUCCESS = 'FILTER_GROUPS_SUCCESS';
export const FILTER_GROUPS_FAILURE = 'FILTER_GROUPS_FAILURE';

//filterGroupsDetail Actions
export const FILTER_GROUPS_DETAIL = 'FILTER_GROUPS_DETAIL';
export const FILTER_GROUPS_DETAIL_SUCCESS = 'FILTER_GROUPS_DETAIL_SUCCESS';
export const FILTER_GROUPS_DETAIL_FAILURE = 'FILTER_GROUPS_DETAIL_FAILURE';

//filterRoles Actions
export const FILTER_ROLES = 'FILTER_ROLES';
export const FILTER_ROLES_SUCCESS = 'FILTER_ROLES_SUCCESS';
export const FILTER_ROLES_FAILURE = 'FILTER_ROLES_FAILURE';

//filterRolesDetail Actions
export const FILTER_ROLES_DETAIL = 'FILTER_ROLES_DETAIL';
export const FILTER_ROLES_DETAIL_SUCCESS = 'FILTER_ROLES_DETAIL_SUCCESS';
export const FILTER_ROLES_DETAIL_FAILURE = 'FILTER_ROLES_DETAIL_FAILURE';

export const FILTER_ROLE_AUTH = 'FILTER_ROLE_AUTH';
export const FILTER_ROLE_AUTH_SUCCESS = 'FILTER_ROLE_AUTH_SUCCESS';
export const FILTER_ROLE_AUTH_FAILURE = 'FILTER_ROLE_AUTH_FAILURE';
export const CLEAR_ROLE_AUTH_DATA = 'CLEAR_ROLE_AUTH_DATA';

export const FILTER_ROLEFORUSER = 'FILTER_ROLEFORUSER';
export const FILTER_ROLEFORUSER_SUCCESS = 'FILTER_ROLEFORUSER_SUCCESS';
export const FILTER_ROLEFORUSER_FAILURE = 'FILTER_ROLEFORUSER_FAILURE';

export const FILTER_GROUPFORUSER = 'FILTER_GROUPFORUSER';
export const FILTER_GROUPFORUSER_SUCCESS = 'FILTER_GROUPFORUSER_SUCCESS';
export const FILTER_GROUPFORUSER_FAILURE = 'FILTER_GROUPFORUSER_FAILURE';

export const FILTER_ROLEFORGROUP = 'FILTER_ROLEFORGROUP';
export const FILTER_ROLEFORGROUP_SUCCESS = 'FILTER_ROLEFORGROUP_SUCCESS';
export const FILTER_ROLEFORGROUP_FAILURE = 'FILTER_ROLEFORGROUP_FAILURE';

export const CLEAR_ROLES_DATA = 'CLEAR_ROLES_DATA';
export const CLEAR_ROLEFORUSER_DATA = 'CLEAR_ROLEFORUSER_DATA';

export const CLEAR_GROUPS_DATA = 'CLEAR_GROUPS_DATA';
export const CLEAR_GROUPFORUSER_DATA = 'CLEAR_GROUPFORUSER_DATA';

export const CLEAR_ROLEFORGROUP_DATA = 'CLEAR_ROLEFORGROUP_DATA';



//调度中心
export const FILTER_DISPATCH = 'FILTER_DISPATCH'
export const FILTER_DISPATCH_SUCCESS = 'FILTER_DISPATCH_SUCCESS'
export const FILTER_DISPATCH_FAILURE = 'FILTER_DISPATCH_FAILURE'

export const FILTER_DISPATCH_DETAIL = 'FILTER_DISPATCH_DETAIL'
export const FILTER_DISPATCH_DETAIL_SUCCESS = 'FILTER_DISPATCH_DETAIL_SUCCESS'
export const FILTER_DISPATCH_DETAIL_FAILURE = 'FILTER_DISPATCH_DETAIL_FAILURE'



//爬虫统计
export const FILTER_CRAWLERSTA = 'FILTER_CRAWLERSTA'
export const FILTER_CRAWLERSTA_SUCCESS = 'FILTER_CRAWLERSTA_SUCCESS'
export const FILTER_CRAWLERSTA_FAILURE = 'FILTER_CRAWLERSTA_FAILURE'

export const FILTER_CRAWLERSTA_DETAIL = 'FILTER_CRAWLERSTA_DETAIL'
export const FILTER_CRAWLERSTA_DETAIL_SUCCESS = 'FILTER_CRAWLERSTA_DETAIL_SUCCESS'
export const FILTER_CRAWLERSTA_DETAIL_FAILURE = 'FILTER_CRAWLERSTA_DETAIL_FAILURE'

//连接状态
export const FILTER_CONNECTIONS = 'FILTER_CONNECTIONS'
export const FILTER_CONNECTIONS_SUCCESS = 'FILTER_CONNECTIONS_SUCCESS'
export const FILTER_CONNECTIONS_FAILURE = 'FILTER_CONNECTIONS_FAILURE'

//排行榜


//用户权限
export const FILTER_AUTHORITIES = 'FILTER_AUTHORITIES'
export const FILTER_AUTHORITIES_SUCCESS = 'FILTER_AUTHORITIES_SUCCESS'
export const FILTER_AUTHORITIES_FAILURE = 'FILTER_AUTHORITIES_FAILURE'

export const FILTER_AUTHORITIES_DETAIL = 'FILTER_AUTHORITIES_DETAIL'
export const FILTER_AUTHORITIES_DETAIL_SUCCESS = 'FILTER_AUTHORITIES_DETAIL_SUCCESS'
export const FILTER_AUTHORITIES_DETAIL_FAILURE = 'FILTER_AUTHORITIES_DETAIL_FAILURE'


//filterLogDictionaryData Actions


//filterLogDictionaryDetail Actions
export const FILTER_LOGDICTIONARY_DETAIL = 'FILTER_LOGDICTIONARY_DETAIL';
export const FILTER_LOGDICTIONARY_DETAIL_SUCCESS = 'FILTER_LOGDICTIONARY_DETAIL_SUCCESS';
export const FILTER_LOGDICTIONARY_DETAIL_FAILURE = 'FILTER_LOGDICTIONARY_DETAIL_FAILURE';

//投票管理
export const FILTER_VOTES = 'FILTER_VOTES'
export const FILTER_VOTES_SUCCESS = 'FILTER_VOTES_SUCCESS'
export const FILTER_VOTES_FAILURE = 'FILTER_VOTES_FAILURE'

export const FILTER_VOTES_DETAIL = 'FILTER_VOTES_DETAIL'
export const FILTER_VOTES_DETAIL_SUCCESS = 'FILTER_VOTES_DETAIL_SUCCESS'
export const FILTER_VOTES_DETAIL_FAILURE = 'FILTER_VOTES_DETAIL_FAILURE'

//投票选项
export const FILTER_VOTESOPTIONS = 'FILTER_VOTESOPTIONS'
export const FILTER_VOTESOPTIONS_SUCCESS = 'FILTER_VOTESOPTIONS_SUCCESS'
export const FILTER_VOTESOPTIONS_FAILURE = 'FILTER_VOTESOPTIONS_FAILURE'

export const FILTER_VOTESOPTIONS_DETAIL = 'FILTER_VOTESOPTIONS_DETAIL'
export const FILTER_VOTESOPTIONS_DETAIL_SUCCESS = 'FILTER_VOTESOPTIONS_DETAIL_SUCCESS'
export const FILTER_VOTESOPTIONS_DETAIL_FAILURE = 'FILTER_VOTESOPTIONS_DETAIL_FAILURE'

//SeedId下拉框
export const FILTER_CHANNELSELECT = 'FILTER_CHANNELSELECT'
export const FILTER_CHANNELSELECT_SUCCESS = 'FILTER_CHANNELSELECT_SUCCESS'
export const FILTER_CHANNELSELECT_FAILURE = 'FILTER_CHANNELSELECT_FAILURE'
export const FILTER_CREATORSELECT = 'FILTER_CREATORSELECT'
export const FILTER_CREATORSELECT_SUCCESS = 'FILTER_CREATORSELECT_SUCCESS'
export const FILTER_CREATORSELECT_FAILURE = 'FILTER_CREATORSELECT_FAILURE'
export const FILTER_SEEDSELECT = 'FILTER_SEEDSELECT'
export const FILTER_SEEDSELECT_SUCCESS = 'FILTER_SEEDSELECT_SUCCESS'
export const FILTER_SEEDSELECT_FAILURE = 'FILTER_SEEDSELECT_FAILURE'
export const CLEAR_SEEDSELECT_DATA = 'CLEAR_SEEDSELECT_DATA'

//扩展信息
export const FILTER_EXTENDINFOMATION = 'FILTER_EXTENDINFOMATION'
export const FILTER_EXTENDINFOMATION_SUCCESS = 'FILTER_EXTENDINFOMATION_SUCCESS'
export const FILTER_EXTENDINFOMATION_FAILURE = 'FILTER_EXTENDINFOMATION_FAILURE'

export const FILTER_EXTENDINFOMATION_DETAIL = 'FILTER_EXTENDINFOMATION_DETAIL'
export const FILTER_EXTENDINFOMATION_DETAIL_SUCCESS = 'FILTER_EXTENDINFOMATION_DETAIL_SUCCESS'
export const FILTER_EXTENDINFOMATION_DETAIL_FAILURE = 'FILTER_EXTENDINFOMATION_DETAIL_FAILURE'


